baseURL = 'https://landhund.github.io/'
languageCode = 'en-us'
title = 'Mad CAD IT'
theme = "hello-friend-ng"
enableEmoji     = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false
PygmentsCodeFences = true
PygmentsStyle = "monokai"
paginate  = 10
rssLimit  = 100
copyright = "MIT License"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

canonifyURLs = true

enableGitInfo = true

[security.exec]
    allow = ['^asciidoctor$']
[params]
    gitURL = 'https://github.com/Landhund/Landhund.github.io'
    custom_css = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"]
    dateform        = "January 2, 2006"
    dateformShort   = "Jan 2, '06"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "An Electrical Engineer battles with IT and CAD Software"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = true

    # Show a global language switcher in the navigation bar
    enableGlobalLanguageMenu = false

    # Metadata mostly used in document's head
    description = "An electrical engineer battles with IT and CAD software"
    keywords = "homepage, blog"
    images = [""]
    [params.footer]
        trademark = 2024
        rss = true
        copyright = true
        author = true

        topText = ["<a href=\"https://www.buymeacoffee.com/felixdreie3\" target=\"_blank\">Buy Me A Coffee</a>"]
        bottomText = [
        "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
        "Hosted on <a href=\"https://github.com/Landhund/Landhund.github.io\">GitHub Pages</a>"
        ]
    [params.logo]
        logoMark     = "$"
        logoText     = "MCI> cd /home/"
        logoHomeLink = "/"
    [params.author]
      name = "Felix Dreier"
      email = "felix@mad-cad-it.com"
[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 5
        ordered = false
    [markup.asciidocExt]
        workingFolderCurrent = true
        [markup.asciidocExt.attributes]
            allow-uri-read = ""
            source-highlighter = "rouge"
            rouge-css = "style"
            rouge-style = "thankful_eyes"
            #imagesdir = "./images"
            icons = "font"
[security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
[taxonomies]
    category = "blog"
    tag      = "tags"
    # series   = "series"
    # series   = "series"
[permalinks]
  posts = "/posts/:year/:month/:title/"
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 10

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = 1
  [[menu.main]]
    identifier = "dev-log"
    name       = "Dev Log"
    url        = "dev-log/"
    weight     = 100
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
