---
title: "Test Post, Please Ignore"
date: 2023-09-03T09:36:00+02:00
draft: false
---

:icons: font

## Introduction

Hi, this is the first test-post on my new blog!
I have almost _no_ idea what I'm doing, but so far it seems to work out!

## Code Block Test

[source,java]
----
class Hello {
    String hello() {
        return "Hello";
    }
}
----

## Admonitions Test

[NOTE]
====
Esse aliquip pariatur laboris ea duis nisi ut in exercitation mollit dolore culpa. Pariatur commodo pariatur do qui qui culpa nostrud. Consequat deserunt dolore esse amet deserunt velit commodo fugiat mollit laboris non. Labore est irure consectetur laborum sunt sit est et labore voluptate quis. Ea culpa eiusmod voluptate voluptate tempor adipisicing consectetur in proident duis minim exercitation laborum. Esse labore sint in consequat dolore veniam excepteur ex laborum nisi. Minim adipisicing veniam do ea nulla.

Velit amet ad proident dolor sint cillum reprehenderit. Dolore irure tempor est velit cupidatat enim pariatur. Aute pariatur exercitation laboris anim id voluptate minim. Proident laboris laborum dolor nostrud ut sunt tempor id et. Aliqua consectetur voluptate tempor magna. Occaecat irure qui aliqua occaecat.
====

NOTE: Test Note V2

[CAUTION]
====
This is a CAUTION
====

[WARNING]
====
This is a WARNING
====

[TIP]
====
This is a TIP
====

[IMPORTANT]
====
This is IMPORTANT
====
